<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>bas</string>
		<string>qb</string>
	</array>
	<key>name</key>
	<string>QBasic</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.qbasic</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Comment</string>
			<key>match</key>
			<string>(').*</string>
			<key>name</key>
			<string>comment.line.qbasic</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Delimiter</string>
			<key>match</key>
			<string>[,:;]</string>
			<key>name</key>
			<string>meta.delimiter.object.qbasic</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keyword</string>
			<key>match</key>
			<string>\b((END )?IF|(END )?SELECT|(RESUME )?NEXT|CASE|CLOSE|DO|ELSE|FOR|GOSUB|GOTO|LOOP|ON|OPEN|RETURN|THEN|TO|UNTIL|WHILE)\b</string>
			<key>name</key>
			<string>keyword.control.qbasic</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Operator</string>
			<key>match</key>
			<string>(\+|=|&lt;|&gt;|&lt;&gt;|AND|OR)</string>
			<key>name</key>
			<string>keyword.operator.qbasic</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Function</string>
			<key>match</key>
			<string>\b(CHR\$|CLS|COLOR|DATA|INPUT|INT|KEY|LEN|LINE|LOCATE|PALETTE|PLAY|PRINT|PSET|PUT|REDIM|RND|SCREEN|TAB|VIEW)\b</string>
			<key>name</key>
			<string>support.function.qbasic</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Numeric</string>
			<key>match</key>
			<string>\b(\d(\.\d)?)+</string>
			<key>name</key>
			<string>constant.numeric.qbasic</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Global</string>
			<key>match</key>
			<string>\b\w+\$</string>
			<key>name</key>
			<string>constant.global.qbasic</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.qbasic</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>SUB</string>
			<key>match</key>
			<string>^(\w+):</string>
			<key>name</key>
			<string>meta.function.qbasic</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Brace, round</string>
			<key>match</key>
			<string>[\(\)]</string>
			<key>name</key>
			<string>meta.brace.round.qbasic</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Brace, curly</string>
			<key>match</key>
			<string>[\{\}]</string>
			<key>name</key>
			<string>meta.brace.curly.qbasic</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\w+\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.array.qbasic</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>Array</string>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.array.qbasic</string>
				</dict>
			</dict>
			<key>name</key>
			<string>other.array.qbasic</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(")</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.qbasic</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>String, double-quoted</string>
			<key>end</key>
			<string>(")</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.qbasic</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.qbasic</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>comment</key>
					<string>Escaped double-quote inside double-quoted string</string>
					<key>match</key>
					<string>(\\")</string>
					<key>name</key>
					<string>constant.character.escape.qbasic</string>
				</dict>
				<dict>
					<key>comment</key>
					<string>Single quote inside double-quoted string</string>
					<key>match</key>
					<string>(')</string>
					<key>name</key>
					<string>other.qbasic</string>
				</dict>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.qbasic</string>
	<key>uuid</key>
	<string>e7de52b7-8378-4396-848e-e9da04e24ddb</string>
</dict>
</plist>