A% = 20
PRINT "A=", A%

PRINT "TEST1"
IF A% < 30 THEN BEGIN
  PRINT A%, "LT 20"
END IF
PRINT "TEST1 DONE"

PRINT "TEST2"
IF A% > 30 THEN BEGIN
  PRINT A%, "GT 20"
END IF
PRINT "TEST2 DONE"

PRINT "TEST3"
IF A% < 20 THEN BEGIN
  PRINT A%, "LT 20"
ELSE BEGIN
  PRINT A%, "GE 20"
END IF
PRINT "TEST3 DONE"

PRINT "TEST4"
IF A% <= 20 THEN BEGIN
  PRINT A%, "LE 20"
ELSE BEGIN
  PRINT A%, "GT 20"
END IF
PRINT "TEST4 DONE"

PRINT "TEST5"
FOR I% = 19 TO 21
  IF I% < 20 THEN BEGIN
    PRINT I%, "LT 20"
    IF I% = 19 THEN BEGIN
      PRINT I%, "EQ 19"
    ELSE BEGIN
      PRINT I%, "NE 19"
    END IF
  ELSE BEGIN
    PRINT I%, "GE 20"
    IF I% = 20 THEN BEGIN
      PRINT I%, "EQ 20"
    ELSE BEGIN
      PRINT I%, "NE 20"
    END IF
  END IF
NEXT
PRINT "TEST5 DONE"
