name: Android CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Update versionCode
      uses: chkfung/android-version-actions@v1.2.1
      with:
        gradlePath: app/build.gradle.kts
        versionCode: ${{github.run_number}}

    - name: Build with Gradle
      run: ./gradlew build

    - name: Assemble Debug APK
      run: |
        ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: apk
        path: app/build/outputs/apk/debug/app-debug.apk 
