name: Android CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    concurrency:
      group: android-ci-${{ github.ref }}
      cancel-in-progress: true

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Build with Gradle
      run: ./gradlew build

    - name: Assemble Debug APK
      run: |
        ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v1
      with:
        name: apk
        path: app/build/outputs/apk/debug/app-debug.apk 
